version: '3.3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql/data
    networks:
      - service-network

  pgadmin4:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    hostname: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    volumes:
      - ./volumes/pgadmin:/var/lib/pgadmin
    networks:
      - service-network
    depends_on:
      - postgres

networks:
  service-network:
    driver: bridge
